version: 2.1

orbs:
  welcome: circleci/welcome-orb@0.4.1
jobs:
  print-hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo hello!"
  print-world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Say world"
          command: "echo world"
  print-my-name:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "print my name"
          command: |
            echo ${MY_ENV_VAR}
workflows:
  say-hello-workflow:
    jobs:
      - print-hello
      - print-world:
          requires:
            - print-hello
      - print-my-name:
          requires:
            - print-hello
            - print-world
